name: GroupiNA
favicon: null
layout_spectrum: 0.99037
typography_spectrum: 0.31206
title: GroupiNA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6ebcd'
    - '#35bc56'
    - '#125e5a'
    - '#cc8e5a'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
